version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    container_name: nginx
    ports:
      - '8080:80'
    depends_on:
      - app
      - db

    networks:
      - amestris_network

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && npm run start"
    networks:
      - amestris_network 
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0    
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - amestris_network

networks:
  amestris_network:
    driver: bridge